export const userData = {
   tenth_institution: "",
   tenth_marks: "",
   tenth_mode_of_study: "",
   twelfth_institution: "",
   twelfth_marks: "",
   twelfth_mode_of_study: "",
   undergraduate_institution: "",
   undergraduate_marks: "",
   undergraduate_mode_of_study: "",
   postgraduate_institution: "",
   postgraduate_marks: "",
   postgraduate_mode_of_study: "",
   phd_institution: "",
   phd_marks: "",
   phd_mode_of_study: "",
   english_skill: "",
   new_language: "",
   proficiency_in_language: "",
   internship_details: [],
   work_experience: [],
   preferred_course: "",
   preferred_country: "",
   budget: "",
   availing_scholarship: "",
   religion: "",
   caste: "",
   nationality: "",
   intake: "",
   year_of_study: "",
   date_of_birth: "",
};

