const userData = {
   tenth_institution: "",
   tenth_marks: "",
   tenth_mode_of_study: "",
   twelfth_institution: "",
   twelfth_marks: "",
   twelfth_mode_of_study: "",
   undergraduate_institution: "",
   undergraduate_marks: "",
   undergraduate_mode_of_study: "",
   postgraduate_institution: "",
   postgraduate_marks: "",
   postgraduate_mode_of_study: "",
   phd_institution: "",
   phd_marks: "",
   phd_mode_of_study: "",
   english_skill: "",
   new_language: "",
   proficiency_in_language: "",
   language: "",
   certificate: "",
   level_of_proficiency: "",
   language_proficiency: [
      {
         parent: "",
         parentfield: "language_proficiency",
         parenttype: "Student",
         language: "",
         certificate: "",
         level_of_proficiency: "",
      },
   ],
   intern_position: "",
   intern_company_name: "",
   intern_from: "",
   intern_to: "",
   internship_details: [
      {
         parent: "",
         parentfield: "internship_details",
         parenttype: "Student",
         internship_experience: 0,
         intern_position: "",
         intern_company_name: "",
         intern_to: "",
         intern_from: "",
      },
   ],
   work_position: "",
   work_company_name: "",
   work_from: "",
   work_to: "",
   work_experience: [
      {
         parent: "",
         parentfield: "work_experience",
         parenttype: "Student",
         work_position: "",
         work_company_name: "",
         work_to: "",
         work_from: "",
      },
   ],
   preferred_course: "",
   preferred_country: "",
   preferences: [
      {
         parent: "",
         parentfield: "preferences",
         parenttype: "Student",
         preferred_course: "",
         preferred_country: "",
      },
   ],
   budget: "",
   religion: "",
   caste: "",
   nationality: "",
   intake: "",
   year_of_study: "",
   date_of_birth: "",
};
